#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for par_parallelizer
#
#-------------------------------------------------------------------------

subdir = src/backend/par_parallelizer
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

OBJS = par_parallelizer.o

include $(top_srcdir)/src/backend/common.mk
