#-------------------------------------------------------------------------
#
# Makefile for PargreSQL exchange test
#
# Constantin S. Pan     2011    kvapen@gmail.com
#
#-------------------------------------------------------------------------

subdir = src/test/par_exchange
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

#override CFLAGS += $(PTHREAD_CFLAGS)

all: par_merge_test

#par_merge_test: par_merge_test.o
#	$(CC) $(CFLAGS) $(LDFLAGS) $(LIBS) -o $@

#clean distclean maintainer-clean:
#	rm -f par_merge_test$(X) par_merge_test.o
